[package]
license = "MIT"
description = "A meticulously crafted Rust full-stack framework."
name = "threadloom"
version = "0.1.7"
edition = "2021"

[dependencies]
threadloom-core = { path = "../threadloom-core", version = "0.1.17" }
threadloom-macro = { path = "../threadloom-macro", version = "0.1.16" }
threadloom-server = { path = "../threadloom-server", version = "0.1.13" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
threadloom-dom = { path = "../threadloom-dom", version = "0.1.18" }

[dev-dependencies]
trybuild = "1.0"

[features]
default = []
actix = ["threadloom-server/actix"]
lambda = ["threadloom-server/lambda"]
